### ISSUE TITLE
Does not work with mat-date-range-input

### ISSUE THREAD

**Issue by Totati** [Totati/ngx-mat-errors#23]
As MatDateRangeInput does not have a ngControl NgxMatErrors won't initialise.

**Comment by Kyoss79** [comment]
I kind of have the same problem with mat-calendar

**Comment by Totati** [comment]
[There has been a draft ](https://github.com/Totati/ngx-mat-errors/pull/32) in my local repo, but I don't know how that solution would solve your issue, as `MatCalendar` is not a `FormControl`, nor could be put in a `MatFormField`.

**Comment by Kyoss79** [comment]
@Totati nice. I already wrapped the mat-calendar in a component that implements ControlValueAccessor. Maybe if I extend it from _AbstractControl_ it would work with your draft? 😄 

Btw, I love this package. It saves tons of work.
