### ISSUE TITLE
Does not work with Angular 15

### ISSUE THREAD

**Issue by Kyoss79** [Totati/ngx-mat-errors#27]
This does not seem to work with angular 15 :(

Keep up the good work

**Comment by Totati** [comment]
Hi, it's in progress, but I haven't had time to complete it. Will fix this soon.

**Comment by Kyoss79** [comment]
Can you please tell us, when you have planned to do this.

do you need any help in making this work with Angular15+ ?

**Comment by Kyoss79** [comment]
I did dive a little deeper into this.
It seems that in your ngOnInit

`if (!this.control && this.matFormField) {
            this.control = this.matFormField._control;
        }`
the "_control" does not exist yet.

When I moved the code to a ngAfterViewInit, it does seem to work.

Maybe that helps

**Comment by Totati** [comment]
@Kyoss79 I went with using `defer`.
See [release 15.0.0](https://github.com/Totati/ngx-mat-errors/releases/tag/ngx-mat-errors-15.0.0) for changes.
